spring:
  elasticsearch:
    uris: localhost:9200
    socket-timeout: 30
    username: elastic
    password: GNBil+AFXd77UCvb5mVl
#    restclient:
#      ssl:
#        bundle:
  kafka:
    bootstrap-servers: localhost:9092
    streams:
      application-id: kafka-cg-aggregator
      properties:
        allow.create.topics: false
        default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        commit.interval.ms: 1000 # Frequency of commit in ms
        state.dir: /tmp/kafka-streams # Directory location for state store
        num.stream.threads: 2 # Number of stream threads in the application
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: kafka-cg-aggregator
      auto-offset-reset: latest
      allow-auto-create-topics: false

kafka:
  topic:
    input: json-input-topic
    output: aggregated-output-topic

message:
  filter: "xyz"