#xyz:
#  elasticsearch:
#    uris: localhost:9200
#    socket-timeout: 30
#    username: elastic
#    password: GNBil+AFXd77UCvb5mVl
#    index: aggregated-info
#    restclient:
#      ssl:
#        bundle:
spring:
  kafka:
    bootstrap-servers: localhost:9092
    streams:
      application-id: kafka-cg-aggregator-1
      properties:
        schema.registry.url: http://localhost:8081
        default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        default.value.serde: io.confluent.kafka.streams.serdes.avro.GenericAvroSerde
        commit.interval.ms: 1000 # Frequency of commit in ms
        state.dir: /tmp/kafka-streams # Directory location for state store
        num.stream.threads: 3 # Number of stream threads in the application
        connection.max.idle.ms: 900000 # Adjusted max idle time for streams connections
        reconnect.backoff.ms: 1000 # Time to wait before attempting reconnection after disconnection
        reconnect.backoff.max.ms: 10000 # Maximum time to wait before attempting reconnection
        auto.offset.reset: latest
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      group-id: kafka-cg-aggregator
      auto-offset-reset: latest

schema:
  registry:
    url: http://localhost:8081
  specific:
    avro:
      reader: false

kafka:
  topic:
    input: json-input-topic

message:
  filter: "SHIVA_FILTER"

logging:
  level:
    org.apache.kafka.streams.processor.internals.ProcessorStateManager: DEBUG